### ISSUE TITLE
第三步将代码clone到本地超时

### ISSUE THREAD

**Issue by tongqii** [outlookxie/app-todolist#1]
如题，执行git clone git@gitlab.alibaba-inc.com:dingding/demo.git根本下不下来demo

**Comment by codertony** [comment]
同上，有没有人出来说明一下

**Comment by joket1999** [comment]
直接git clone https://github.com/outlookxie/app-todolist ，ReadMe里说的「git@gitlab.alibaba-inc.com」估计是阿里内部的服务器
